package com.wanderwildwood.kotozute.signalstore

import org.signal.libsignal.protocol.IdentityKey
import org.signal.libsignal.protocol.IdentityKeyPair
import org.signal.libsignal.protocol.ecc.ECPrivateKey
import timber.log.Timber

/**
 * The account: who this device is on the account, and the counters that hand out key ids.
 *
 * signal-cli keeps this in a JSON file beside its database, guarded by a process-wide lock and
 * saved after every mutation. That is not available here — Android ends processes rather than
 * shutting them down — so it lives in the same database as the key tables, and every counter
 * moves in the same transaction as the row it indexes. See docs/DECISION-protocol-store.md.
 *
 * The password is the part most easily got wrong: it is **generated by this client before
 * linking**, never sent in the provisioning message and never returned by the server. It is
 * half the account credential for the life of the device. Lose it and the device is not
 * recoverable, only re-linkable.
 */
internal class SignalAccountStore(private val db: ProtocolDatabase) {

    // --- credentials -------------------------------------------------------------------

    data class Credentials(
        val e164: String?,
        val aci: String?,
        val pni: String?,
        val deviceId: Int,
        val password: String?
    ) {
        /** Anything missing means this device cannot authenticate, so do not let it try. */
        val complete: Boolean
            get() = !aci.isNullOrBlank() && !password.isNullOrBlank() && deviceId > 0
    }

    fun credentials(): Credentials = withLock {
        db.readableDatabase.rawQuery(
            "SELECT number, aci, pni, device_id, password FROM account WHERE _id = 1", null
        ).use { c ->
            check(c.moveToFirst()) { "account row missing" }
            Credentials(c.getString(0), c.getString(1), c.getString(2), c.getInt(3), c.getString(4))
        }
    }

    /**
     * Written once, when linking completes. Everything here arrives together in the
     * ProvisionMessage and the registration response, so it is stored together — a half-written
     * account is one that authenticates as nobody.
     */
    fun saveCredentials(e164: String?, aci: String, pni: String?, deviceId: Int, password: String) =
        inTransaction {
            db.writableDatabase.execSQL(
                "UPDATE account SET number = ?, aci = ?, pni = ?, device_id = ?, password = ? WHERE _id = 1",
                arrayOf(e164, aci, pni, deviceId, password)
            )
            Timber.i("signal store: account saved, device id %d", deviceId)
        }

    /** When this device last applied a change to the account's own phone number. */
    fun lastPniChangeAt(): Long = withLock {
        db.readableDatabase.rawQuery(
            "SELECT last_pni_change_timestamp FROM account WHERE _id = 1", null
        ).use { c -> if (c.moveToFirst()) c.getLong(0) else 0L }
    }

    /**
     * Applies a change of the account's own phone number, as the primary made it.
     *
     * Everything in one transaction: the number, the new phone-number identity, and the key
     * material that goes with it. Half-applied, this device would hold a PNI whose identity
     * key it does not have, and every message addressed to that identity would fail to
     * decrypt with nothing to explain why.
     */
    fun applyNumberChange(
        e164: String,
        pni: String,
        pniIdentity: IdentityKeyPair,
        pniRegistrationId: Int,
        serverTimestamp: Long
    ) = inTransaction {
        db.writableDatabase.execSQL(
            "UPDATE account SET number = ?, pni = ?, last_pni_change_timestamp = ? WHERE _id = 1",
            arrayOf<Any?>(e164, pni, serverTimestamp)
        )
        db.writableDatabase.execSQL(
            """
            UPDATE account_identity
            SET identity_public = ?, identity_private = ?, registration_id = ?
            WHERE account_id_type = ?
            """.trimIndent(),
            arrayOf<Any?>(
                pniIdentity.publicKey.serialize(),
                pniIdentity.privateKey.serialize(),
                pniRegistrationId,
                ProtocolDatabase.ACCOUNT_ID_TYPE_PNI
            )
        )
    }

    fun saveProfileKey(profileKey: ByteArray) = inTransaction {
        db.writableDatabase.execSQL(
            "UPDATE account SET profile_key = ? WHERE _id = 1", arrayOf(profileKey)
        )
    }

    // --- identity ----------------------------------------------------------------------

    fun identityKeyPair(accountIdType: Int): IdentityKeyPair? = withLock {
        db.readableDatabase.rawQuery(
            "SELECT identity_public, identity_private FROM account_identity WHERE account_id_type = ?",
            arrayOf(accountIdType.toString())
        ).use { c ->
            if (!c.moveToFirst()) return@use null
            val pub = c.getBlob(0) ?: return@use null
            val priv = c.getBlob(1) ?: return@use null
            IdentityKeyPair(IdentityKey(pub), ECPrivateKey(priv))
        }
    }

    /**
     * The identity and its registration id are written together on purpose. libsignal uses the
     * registration id to recognise a session as belonging to this installation; an identity
     * saved with a stale or zero registration id produces sessions that peers will reject
     * later, for reasons that will not point here.
     */
    fun saveIdentity(accountIdType: Int, keyPair: IdentityKeyPair, registrationId: Int) =
        inTransaction {
            db.writableDatabase.execSQL(
                """
                UPDATE account_identity
                SET identity_public = ?, identity_private = ?, registration_id = ?
                WHERE account_id_type = ?
                """.trimIndent(),
                arrayOf(
                    keyPair.publicKey.serialize(),
                    keyPair.privateKey.serialize(),
                    registrationId,
                    accountIdType
                )
            )
        }

    // --- key id allocation -------------------------------------------------------------

    /**
     * Hands out the next pre key ids and advances the counter in one transaction.
     *
     * This is the operation the research warned about: the counter lives on the account row
     * and the keys live in their own table, and if the process dies between advancing one and
     * writing the other, the next call hands out an id that already exists. The caller is
     * expected to insert the key rows inside [transaction] so the whole thing is one write.
     *
     * Ids wrap at [MAX_KEY_ID] because the wire format carries them in three bytes; a counter
     * allowed past that produces ids the server will not accept.
     */
    fun allocatePreKeyIds(accountIdType: Int, count: Int, insert: (List<Int>) -> Unit) =
        inTransaction {
            val next = counter(accountIdType, "next_pre_key_id")
            val ids = (0 until count).map { (next + it) % MAX_KEY_ID }
            insert(ids)
            setCounter(accountIdType, "next_pre_key_id", (next + count) % MAX_KEY_ID)
        }

    /**
     * The Kyber equivalent, with the same guarantee and for the same reason.
     *
     * Deliberately an allocator rather than a "give me the next id" plus a separate "advance
     * by n": those two calls have a gap between them, and the gap is precisely the race the
     * transaction exists to close.
     */
    fun allocateKyberPreKeyIds(accountIdType: Int, count: Int, insert: (List<Int>) -> Unit) =
        inTransaction {
            val next = counter(accountIdType, "next_kyber_pre_key_id")
            val ids = (0 until count).map { (next + it) % MAX_KEY_ID }
            insert(ids)
            setCounter(accountIdType, "next_kyber_pre_key_id", (next + count) % MAX_KEY_ID)
        }

    fun nextSignedPreKeyId(accountIdType: Int): Int = withLock {
        counter(accountIdType, "next_signed_pre_key_id")
    }

    fun nextKyberPreKeyId(accountIdType: Int): Int = withLock {
        counter(accountIdType, "next_kyber_pre_key_id")
    }

    /** Advancing the counter and recording which key is active is one decision, so one write. */
    fun recordActiveSignedPreKey(accountIdType: Int, keyId: Int) = inTransaction {
        setCounter(accountIdType, "next_signed_pre_key_id", (keyId + 1) % MAX_KEY_ID)
        setCounter(accountIdType, "active_signed_pre_key_id", keyId)
    }

    fun recordActiveLastResortKyberPreKey(accountIdType: Int, keyId: Int) = inTransaction {
        setCounter(accountIdType, "next_kyber_pre_key_id", (keyId + 1) % MAX_KEY_ID)
        setCounter(accountIdType, "active_last_resort_kyber_pre_key_id", keyId)
    }

    fun activeSignedPreKeyId(accountIdType: Int): Int = withLock {
        counter(accountIdType, "active_signed_pre_key_id")
    }

    private fun counter(accountIdType: Int, column: String): Int =
        db.readableDatabase.rawQuery(
            "SELECT $column FROM account_identity WHERE account_id_type = ?",
            arrayOf(accountIdType.toString())
        ).use { c -> if (c.moveToFirst()) c.getInt(0) else 0 }

    private fun setCounter(accountIdType: Int, column: String, value: Int) {
        db.writableDatabase.execSQL(
            "UPDATE account_identity SET $column = ? WHERE account_id_type = ?",
            arrayOf(value, accountIdType)
        )
    }

    // --- plumbing ----------------------------------------------------------------------

    /**
     * The lock and the SQL transaction together. The lock alone would not stop a half-written
     * pair surviving a process death, and the transaction alone would not stop libsignal
     * re-entering from another thread mid-write.
     */
    private inline fun <T> inTransaction(body: () -> T): T = withLock {
        val database = db.writableDatabase
        database.beginTransaction()
        try {
            val result = body()
            database.setTransactionSuccessful()
            result
        } finally {
            database.endTransaction()
        }
    }

    private inline fun <T> withLock(body: () -> T): T {
        db.lock.lock()
        try {
            return body()
        } finally {
            db.lock.unlock()
        }
    }

    companion object {
        /** Three bytes on the wire, so ids wrap here rather than being rejected by the server. */
        const val MAX_KEY_ID = 0xFFFFFF
    }
}
